grid_map_topic: /grid_map_filter_demo/filtered_map

grid_map_visualizations:

  - name: elevation_points
    type: point_cloud
    params:
     layer: elevation_averaged
     
  - name: surface_normals
    type: vectors
    params:
     layer_prefix: normal_vectors_
     position_layer: elevation_averaged
     scale: 0.06
     line_width: 0.005
     color: 15600153 # red

  - name: elevation_grid
    type: occupancy_grid
    params:
     layer: traversability
     data_min: 0.0
     data_max: 1.0
